version: '3.2'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  redis-commander:
    platform: linux/amd64
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
  couchdb:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb-0.docker.com
    image: couchdb:latest
    networks:
      network:
        aliases:
          - couchdb-0.docker.com
    ports:
      - '5984:5984'
    volumes:
      - 'couchdb:/opt/couchdb/data'
networks:
  network:
volumes:
  redis-data:
  redis-conf:
  couchdb:
